name: Build and Test
on:
  push:
  pull_request:
  schedule:
    - cron: '15 5 3 * *'
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
          cache: maven
      - name: Build and test
        run: mvn --batch-mode compile test
# TODO: If a release, build platform-native apps and attach to the release
